# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BucketBeanz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Add Parse pods and install
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'

  # Pods for BucketBeanz

  target 'BucketBeanzTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Parse'
  end

  target 'BucketBeanzUITests' do
    # Pods for testing
    pod 'Parse'
  end

end
